package com.test.dao.entry;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeployDbPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public DeployDbPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNull() {
            addCriterion("dbName is null");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNotNull() {
            addCriterion("dbName is not null");
            return (Criteria) this;
        }

        public Criteria andDbNameEqualTo(String value) {
            addCriterion("dbName =", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotEqualTo(String value) {
            addCriterion("dbName <>", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThan(String value) {
            addCriterion("dbName >", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThanOrEqualTo(String value) {
            addCriterion("dbName >=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThan(String value) {
            addCriterion("dbName <", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThanOrEqualTo(String value) {
            addCriterion("dbName <=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLike(String value) {
            addCriterion("dbName like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotLike(String value) {
            addCriterion("dbName not like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameIn(List<String> values) {
            addCriterion("dbName in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotIn(List<String> values) {
            addCriterion("dbName not in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameBetween(String value1, String value2) {
            addCriterion("dbName between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotBetween(String value1, String value2) {
            addCriterion("dbName not between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBIsNull() {
            addCriterion("isDoDeployDB is null");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBIsNotNull() {
            addCriterion("isDoDeployDB is not null");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBEqualTo(Integer value) {
            addCriterion("isDoDeployDB =", value, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBNotEqualTo(Integer value) {
            addCriterion("isDoDeployDB <>", value, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBGreaterThan(Integer value) {
            addCriterion("isDoDeployDB >", value, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDoDeployDB >=", value, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBLessThan(Integer value) {
            addCriterion("isDoDeployDB <", value, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBLessThanOrEqualTo(Integer value) {
            addCriterion("isDoDeployDB <=", value, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBIn(List<Integer> values) {
            addCriterion("isDoDeployDB in", values, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBNotIn(List<Integer> values) {
            addCriterion("isDoDeployDB not in", values, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBBetween(Integer value1, Integer value2) {
            addCriterion("isDoDeployDB between", value1, value2, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoDeployDBNotBetween(Integer value1, Integer value2) {
            addCriterion("isDoDeployDB not between", value1, value2, "isDoDeployDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBIsNull() {
            addCriterion("isDoTestDB is null");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBIsNotNull() {
            addCriterion("isDoTestDB is not null");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBEqualTo(Integer value) {
            addCriterion("isDoTestDB =", value, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBNotEqualTo(Integer value) {
            addCriterion("isDoTestDB <>", value, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBGreaterThan(Integer value) {
            addCriterion("isDoTestDB >", value, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDoTestDB >=", value, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBLessThan(Integer value) {
            addCriterion("isDoTestDB <", value, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBLessThanOrEqualTo(Integer value) {
            addCriterion("isDoTestDB <=", value, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBIn(List<Integer> values) {
            addCriterion("isDoTestDB in", values, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBNotIn(List<Integer> values) {
            addCriterion("isDoTestDB not in", values, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBBetween(Integer value1, Integer value2) {
            addCriterion("isDoTestDB between", value1, value2, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoTestDBNotBetween(Integer value1, Integer value2) {
            addCriterion("isDoTestDB not between", value1, value2, "isDoTestDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBIsNull() {
            addCriterion("isDoPlatformDB is null");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBIsNotNull() {
            addCriterion("isDoPlatformDB is not null");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBEqualTo(Integer value) {
            addCriterion("isDoPlatformDB =", value, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBNotEqualTo(Integer value) {
            addCriterion("isDoPlatformDB <>", value, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBGreaterThan(Integer value) {
            addCriterion("isDoPlatformDB >", value, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDoPlatformDB >=", value, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBLessThan(Integer value) {
            addCriterion("isDoPlatformDB <", value, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBLessThanOrEqualTo(Integer value) {
            addCriterion("isDoPlatformDB <=", value, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBIn(List<Integer> values) {
            addCriterion("isDoPlatformDB in", values, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBNotIn(List<Integer> values) {
            addCriterion("isDoPlatformDB not in", values, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBBetween(Integer value1, Integer value2) {
            addCriterion("isDoPlatformDB between", value1, value2, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoPlatformDBNotBetween(Integer value1, Integer value2) {
            addCriterion("isDoPlatformDB not between", value1, value2, "isDoPlatformDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBIsNull() {
            addCriterion("isDoProductDB is null");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBIsNotNull() {
            addCriterion("isDoProductDB is not null");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBEqualTo(Integer value) {
            addCriterion("isDoProductDB =", value, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBNotEqualTo(Integer value) {
            addCriterion("isDoProductDB <>", value, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBGreaterThan(Integer value) {
            addCriterion("isDoProductDB >", value, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDoProductDB >=", value, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBLessThan(Integer value) {
            addCriterion("isDoProductDB <", value, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBLessThanOrEqualTo(Integer value) {
            addCriterion("isDoProductDB <=", value, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBIn(List<Integer> values) {
            addCriterion("isDoProductDB in", values, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBNotIn(List<Integer> values) {
            addCriterion("isDoProductDB not in", values, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBBetween(Integer value1, Integer value2) {
            addCriterion("isDoProductDB between", value1, value2, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andIsDoProductDBNotBetween(Integer value1, Integer value2) {
            addCriterion("isDoProductDB not between", value1, value2, "isDoProductDB");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNull() {
            addCriterion("addUser is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNotNull() {
            addCriterion("addUser is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserEqualTo(String value) {
            addCriterion("addUser =", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotEqualTo(String value) {
            addCriterion("addUser <>", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThan(String value) {
            addCriterion("addUser >", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThanOrEqualTo(String value) {
            addCriterion("addUser >=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThan(String value) {
            addCriterion("addUser <", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThanOrEqualTo(String value) {
            addCriterion("addUser <=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLike(String value) {
            addCriterion("addUser like", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotLike(String value) {
            addCriterion("addUser not like", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserIn(List<String> values) {
            addCriterion("addUser in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotIn(List<String> values) {
            addCriterion("addUser not in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserBetween(String value1, String value2) {
            addCriterion("addUser between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotBetween(String value1, String value2) {
            addCriterion("addUser not between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creatTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creatTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("creatTime =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("creatTime <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("creatTime >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creatTime >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("creatTime <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("creatTime <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("creatTime in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("creatTime not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("creatTime between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("creatTime not between", value1, value2, "creatTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deploy_db_plan
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deploy_db_plan
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}